import { type ClassValue, clsx } from 'clsx'
import { extendTailwindMerge } from 'tailwind-merge'

/**
 * tailwind-merge kennt die Namen aus app.css nicht von selbst. Ohne diese
 * Liste hielte es z. B. `text-16` für eine Farbe und `px-md px-lg` nicht für
 * einen Konflikt. Die Werte spiegeln §4 von app.css.
 */
const twMerge = extendTailwindMerge({
  extend: {
    theme: {
      text: [
        '10',
        '11',
        '12',
        '13',
        '14',
        '16',
        '18',
        '20',
        '22',
        '24',
        '26',
        '30',
        '32',
        '34',
        '40',
        '48',
        '60',
        'btn-lg',
        'btn-md',
        'btn-sm',
        'btn-xx-sm',
        'btn-xxxx-sm',
      ],
      spacing: [
        'zero',
        'xxxs',
        'xxs',
        'xs',
        'sm',
        'md-sm',
        'md',
        'md-l',
        'lg',
        'xl',
        'xxl',
        'xxxl',
        'card-default-frame',
        'card-default-content',
        'card-default-content-gap',
        'card-compact-frame',
        'card-compact-content',
        'card-with-reviews-frame-top',
        'card-with-reviews-gap',
        'card-category-sm-frame',
        'card-category-sm-content',
        'card-category-md-frame',
        'card-category-md-content',
        'card-featured-frame',
        'card-featured-gap',
        'card-featured-content-gap',
        'card-featured-frame-top',
        'card-blog-frame',
        'card-blog-gap',
        'card-discovery-frame',
        'card-discovery-frame-top',
        'card-discovery-gap',
        'card-discovery-content',
        'card-discovery-content-gap',
        'card-review-frame',
        'card-review-frame-top',
        'card-review-content',
        'card-review-content-gap',
        'card-purchase-frame',
        'card-purchase-gap',
        'card-purchase-content',
        'card-purchase-content-gap',
        'card-voucher-frame',
        'card-voucher-content',
        'card-promotion-frame',
        'card-promotion-content',
        'card-image-gap',
        'megacard-frame',
        'megacard-content',
      ],
      container: [
        'block-double-max',
        'block-inline-min',
        'block-max',
        'block-min',
        'btn-max',
        'btn-min',
        'btn-payment-max',
        'card-blog-max',
        'card-blog-min',
        'card-category-md-max',
        'card-category-md-min',
        'card-category-sm-max',
        'card-category-sm-min',
        'card-compact-max',
        'card-compact-min',
        'card-default-max',
        'card-default-min',
        'card-discovery-column-min',
        'card-discovery-hover-max',
        'card-discovery-max',
        'card-discovery-min',
        'card-featured-max',
        'card-featured-min',
        'card-image',
        'card-promotion-max',
        'card-promotion-min',
        'card-review-max',
        'card-review-min',
        'card-voucher-max',
        'card-voucher-min',
        'fieldset-min',
        'footer-header-max',
        'icon-counter-min',
        'impact-scale-max',
        'impact-scale-min',
        'list-item-img-min',
        'megacard-max',
        'megacard-min',
        'nav-block-max',
        'nav-block-min',
        'nuss-abo-cancellation-status-max',
        'overlay-message-max',
        'overlay-message-min',
        'panel-max',
        'panel-min',
        'product-img-max',
        'product-img-min',
        'product-img-thumbnail-max',
        'product-img-thumbnail-row-min',
        'product-page-column-min',
        'search-max',
        'search-min',
        'subscription-management-max',
      ],
      leading: ['tighter', 'tight', 'heading', 'body', 'relaxed'],
      tracking: ['tight', 'normal', 'wide'],
      font: ['display', 'accent-one', 'accent-two', 'body'],
    },
  },
})

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
